packages:
    - "sdk"
    - "tooling/*"
    - "examples/*"

allowBuilds:
    bufferutil: false
    esbuild: true
    utf-8-validate: false

ignoredBuiltDependencies:
    - bufferutil
    - utf-8-validate

onlyBuiltDependencies:
    - esbuild
